In [2]:
import sqlite3
import pandas as pd

# Connexion à la base de données
conn = sqlite3.connect('C:\\Users\\oumar\OneDrive\\Bureau\\Projet_Escalade\\boolder.db')
cursor = conn.cursor()

# Exécution d'une requête SQL et chargement des résultats dans un DataFrame
boolder = pd.read_sql_query("SELECT * FROM problems", conn)

In [3]:
#close la bdd
conn.close()

In [4]:
import random
from datetime import datetime, timedelta

In [5]:
# Charger les données météo à partir d'un fichier Excel
weather_data = pd.read_excel("C:\\Users\\oumar\\OneDrive\\Bureau\\Projet_Escalade\\df.xlsx")
weather_data['date'] = pd.to_datetime(weather_data['date'], format='%d/%m/%Y')
weather_data

,Unnamed: 0,date,tmp_max (°C),tmp_min (°C),precipitation (%),wind (Km/h),humidity (%)
0,0,2024-05-15,20,9.5,"3,2",18.5,80.5
1,1,2024-05-14,21.5,8.5,"1,7",15,75
2,2,2024-05-13,19.7,10,"3,5",14,77.7
3,3,2024-05-12,19.7,10,"2,6",16.7,79
4,4,2024-05-11,20.7,10,"0,1",17.3,75
5,5,2024-05-10,19.7,9.7,"2,7",19,77
6,6,2024-05-09,18.3,8.7,"11,7",16,81.7
7,7,2024-05-08,19.3,8.7,"0,1",15,79.7
8,8,2024-05-07,19,10,"4,3",14.3,79
9,9,2024-05-06,19,8,"2,2",12.3,78.3
10,10,2024-05-05,19,9,"3,3",15.3,79.3
11,11,2024-05-04,18.7,8.3,"1,1",14.7,74.7
12,12,2024-05-03,17,5.7,"0,7",20,74
13,13,2024-05-02,14.3,7,"0,3",18.7,79.3
14,14,2024-05-01,17.3,8.7,"1,6",12.7,74.7
15,15,2024-04-30,16.3,7.7,"1,4",19,78
16,16,2024-04-29,17,8,"0,9",12,78
17,17,2024-04-28,18.5,8.5,"5,4",20,79.5
18,18,2024-04-27,19,5.5,"2,6",20,76.5
19,19,2024-04-26,14,4.7,"0,5",14.7,73.7
20,20,2024-04-25,12.3,4,"1,3",13.7,75.3
21,21,2024-04-24,10,6,"3,9",20.3,81
22,22,2024-04-23,12.3,5.7,"6,2",23.3,80
23,23,2024-04-22,13.3,4.7,"3,9",25.3,75.7
24,24,2024-04-21,13.3,3.3,"1,5",18.7,70
25,25,2024-04-20,"12,3","4,7","0,2",21,"68,7"
26,26,2024-04-19,"14,7","5,3","0,6","18,7",73
27,27,2024-04-18,13.7,3.7,0,21,70.7
28,28,2024-04-17,13.3,5,"1,9",20.7,73.7
29,29,2024-04-16,15.7,5.7,"0,4",18.7,70
30,30,2024-04-15,15.3,7.3,"2,1",21.3,74.3
31,31,2024-04-14,16.7,7.7,"0,3",14.7,73
32,32,2024-04-13,17,9.3,"1,1",18,74.3
33,33,2024-04-12,17,9,"6,2",17.7,74.3
34,34,2024-04-11,15.3,5.3,"0,3",19,75
35,35,2024-04-10,14,3.7,"0,5",16,70
36,36,2024-04-09,12.3,4.7,"1,3",20,72.7
37,37,2024-04-08,13.3,5,"6,6",19.3,80
38,38,2024-04-07,13,7.7,"2,4",23.3,80.3
39,39,2024-04-06,15.7,7,"1,3",23,75.3
40,40,2024-04-05,14.3,6,0,17.3,74.7
41,41,2024-04-04,12.7,3.7,"3,3",28.7,69.7
42,42,2024-04-03,13,3.3,"1,9",23,70.3
43,43,2024-04-02,10.3,3.7,"0,8",26.7,78
44,44,2024-04-01,8.7,4.7,"5,8",30.7,86

In [6]:
# Fonction pour générer une date aléatoire entre deux dates données
def date_aleatoire(debut, fin):
    # Convertir les dates en objets datetime
    debut_date = datetime.strptime(debut, '%Y-%m-%d')
    fin_date = datetime.strptime(fin, '%Y-%m-%d')
    
    # Calculer la plage de jours entre les dates
    plage_jours = (fin_date - debut_date).days
    
    # Générer un décalage aléatoire dans la plage de jours
    offset_jours = random.randint(0, plage_jours)
    
    # Ajouter le décalage aléatoire à la date de début
    random_date = debut_date + timedelta(days=offset_jours)
    
    return random_date

In [7]:
# Fonction pour récupérer les données météo pour une date donnée
def get_weather_by_date(df, date_str):
    date = pd.to_datetime(date_str, format='%d/%m/%Y')
    weather_on_date = df[df['date'] == date]
    if not weather_on_date.empty:
        return weather_on_date
    else:
        print(f"La date {date_str} n'existe pas dans les données.")
        return None


x = get_weather_by_date(weather_data, '14/05/2024')
x

,Unnamed: 0,date,tmp_max (°C),tmp_min (°C),precipitation (%),wind (Km/h),humidity (%)
1,1,2024-05-14,21.5,8.5,"1,7",15,75

In [8]:
# Fonction pour calculer un score météo basé sur différents paramètres météorologiques
def calculate_weather_score(df):
    # Normaliser les paramètres (ajustez les seuils selon vos besoins)
    humidity_score = max(0, min(5, 5 - (float(df['humidity (%)'].str.replace(',', '.').iloc[0]) / 20)))  # Humidité de 0 à 100%
    precipitation_score = max(0, min(5, 5 - (float(df['precipitation (%)'].str.replace(',', '.').iloc[0]) / 20)))  # Précipitations de 0 à 100%
    temp_max_score = max(0, min(5, (float(df['tmp_max (°C)'].str.replace(',', '.').iloc[0]) + 10) / 10))  # Température max de -10°C à 40°C
    temp_min_score = max(0, min(5, (float(df['tmp_min (°C)'].str.replace(',', '.').iloc[0]) + 10) / 10))  # Température min de -10°C à 40°C
    wind_speed_score = max(0, min(5, 5 - (float(df['wind (Km/h)'].str.replace(',', '.').iloc[0]) / 10)))  # Vitesse du vent de 0 à 50 km/h

    # Moyenne pondérée ou simple des notes
    total_score = (humidity_score + precipitation_score + temp_max_score + temp_min_score + wind_speed_score) / 5

    # Arrondir le score final à la note entière la plus proche
    final_score = round(total_score)

    return final_score

In [9]:
# Fonction pour créer des blocs de données avec des scores météo
def create_blocks(weather_data, boolder):
    debut = '2024-04-01'
    fin = '2024-05-15'
    blocks = {}
    
    # Boucler sur chaque ligne de la bdd
    for idx, row in boolder.iterrows():
        dates = {}
        
        # Générer 40 entrées de dates et notes pour chaque blocks
        for _ in range(40):
            coin = random.randint(0, 100)
            random_date = date_aleatoire(debut, fin).strftime("%d/%m/%Y")
            
            # Une chance sur trois de générer une note aléatoire
            if (coin % 3 == 0):
                note = random.randint(0, 5)
                dates[random_date] = note
            else:
                note = calculate_weather_score(get_weather_by_date(weather_data, random_date))
                dates[random_date] = note

        name = row['name']
        blocks[row['id']] = [name, dates]
   
    return blocks

blocks = create_blocks(weather_data, boolder)

In [10]:
print(blocks[45])

['Jaune 4 ', {'09/04/2024': 5, '26/04/2024': 3, '10/05/2024': 1, '04/05/2024': 3, '11/05/2024': 3, '08/05/2024': 3, '23/04/2024': 2, '11/04/2024': 2, '24/04/2024': 2, '02/04/2024': 1, '01/05/2024': 3, '15/04/2024': 4, '09/05/2024': 3, '17/04/2024': 3, '20/04/2024': 3, '06/05/2024': 3, '29/04/2024': 3, '03/05/2024': 3, '18/04/2024': 3, '27/04/2024': 3, '06/04/2024': 2, '05/05/2024': 3, '12/04/2024': 3, '13/05/2024': 4, '15/05/2024': 3, '16/04/2024': 1}]

In [11]:
# Fonction pour filtrer les données météo pour un bloc donné et ajouter les scores correspondants
def filtered_weather(id, dico):
    weather_data = pd.read_excel("C:\\Users\\oumar\\OneDrive\\Bureau\\Projet_Escalade\\df.xlsx")
    weather_data['date'] = weather_data['date'].astype(str)
    
    # Obtenir les dates du dictionnaire pour le bloc donné
    dico_dates = list(dico[id][1].keys())
    
    # Filtrer les données météorologiques pour ne conserver que les dates présentes dans le dictionnaire
    filtered_weather_data = weather_data[weather_data['date'].isin(dico_dates)]

    # Extraire les notes du dictionnaire et les convertir en DataFrame
    notes = pd.DataFrame(list(dico[id][1].items()), columns=['date', 'note'])

    # Joindre les notes aux données météo filtrées
    data = pd.merge(filtered_weather_data, notes, on='date')
    
    data.dropna(subset=['note'], inplace=True)
    
    return data
    
data_set = filtered_weather(45, blocks)

In [12]:
import requests
import time
import datetime

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By

# Chemin vers l'exécutable ChromeDriver
path = "D:\chromedriver-win64\chromedriver.exe"

# Créer un service pour ChromeDriver
service = Service(path)

# Initialiser le navigateur Chrome avec le service
driver = webdriver.Chrome(service=service)

In [13]:
# Configuration de Selenium pour collecter les données météo actuelle
path = "D:\chromedriver-win64\chromedriver.exe"
service = Service(path)
driver = webdriver.Chrome(service=service)

# Récupération des données météorologiques actuelles à partir du site web
current_date = datetime.date.today()
url = f"https://www.meteoart.com/europe/france/ile-de-france/fontainebleau?page=past-weather#day={current_date.day}&month={current_date.month}"
driver.get(url)
driver.implicitly_wait(10)
driver.find_element(By.CLASS_NAME, "fc-cta-consent").click()
time.sleep(5)
divs_month_data = driver.find_elements(By.CLASS_NAME, "month_data_to_animate")
time.sleep(3)

# Préparer une liste pour les données du jour courant
data=[]
txt = [current_date.strftime("%d/%m/%Y")]
for div in divs_month_data:
    txt.append(div.text)

data.append(txt)

In [14]:
# Créer un DataFrame pour les nouvelles données
labels = ['date', 'tmp_max (°C)', 'tmp_min (°C)', 'precipitation (%)', 'wind (Km/h)', 'humidity (%)']
df = pd.DataFrame(data,columns=labels)
df

,date,tmp_max (°C),tmp_min (°C),precipitation (%),wind (Km/h),humidity (%)
0,27/05/2024,22,9.5,0,17.5,72

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

In [112]:
# Convertir les donné en float 
for column in data_set.columns:
    if data_set[column].dtype == 'object':
        data_set[column] = data_set[column].str.replace(',', '.')
        try:
            data_set[column] = data_set[column].astype(float)
        except ValueError:
            pass  # Ignorer les colonnes qui ne peuvent pas être converties en float

# Séparation des données en entrées (X) et cibles (y)
X = data_set.drop(columns=['note','date','Unnamed: 0'])
y = data_set['note']


# Normalisation des caractéristiques
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Séparation des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [136]:
# Création d'un modèle de régression k-plus proches voisins (KNN)
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train) # Entraîne le modèle sur les données d'entraînement

# Prédiction des valeurs cibles pour les données de test
y_pred = knn.predict(X_test)
y_pred_rounded = [round(pred) for pred in y_pred]

# Calcul de l'erreur quadratique moyenne (MSE) pour évaluer les performances du modèle
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred_rounded)
print(f'Mean Squared Error: {mse}')

'''# Calcul de la precision
from sklearn.metrics import precision_score
prs = precision_score(y_test, y_pred, average = None)
print(f'Precision score: {prs}')'''

Mean Squared Error: 0.16666666666666666

"# Calcul de la precision\nfrom sklearn.metrics import precision_score\nprs = precision_score(y_test, y_pred, average = None)\nprint(f'Precision score: {prs}')"

In [138]:
# Normaliser les nouvelles données
new_df = df.drop(columns=['date'])
new_df = new_df.replace(',', '.', regex=True).astype(float)
new_date_weather_scaled = scaler.transform(new_df)

# Prédire la note pour la nouvelle date
predicted_note = knn.predict(new_date_weather_scaled)
predicted_note_rounded = round(predicted_note[0])
print(f'Predicted Note: {predicted_note_rounded}')

Predicted Note: 3

In [ ]:
'''def main():
    
    import sqlite3
    import pandas as pd

    # Charger les données
    # Connexion à la base de données
    conn = sqlite3.connect('C:\\Users\\oumar\OneDrive\\Bureau\\Projet_Escalade\\boolder.db')
    cursor = conn.cursor()
    
    boolder = pd.read_sql_query("SELECT * FROM problems", conn)
    conn.close()
    
    import random
    from datetime import datetime, timedelta
    
    weather_data = pd.read_excel("C:\\Users\\oumar\\OneDrive\\Bureau\\Projet_Escalade\\df.xlsx")
    weather_data['date'] = pd.to_datetime(weather_data['date'], format='%d/%m/%Y')
    
    
    
    # Créer les blocs
    blocks = create_blocks(weather_data, boolder)

    # Demander à l'utilisateur de choisir un bloc
    while True:
        try:
            block_id = int(input("Veuillez entrer l'ID du block: "))
            if block_id in blocks:
                break
            else:
                print("ID de block invalide. Veuillez réessayer.")
        except ValueError:
            print("Veuillez entrer un nombre entier valide.")

    # Filtrer les données météo pour le bloc choisi
    data_set = filtered_weather(block_id, blocks)
    
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import StandardScaler
    from sklearn.neighbors import KNeighborsRegressor
    
    for column in data_set.columns:
        if data_set[column].dtype == 'object':
            data_set[column] = data_set[column].str.replace(',', '.')
            try:
                data_set[column] = data_set[column].astype(float)
            except ValueError:
                pass
        
    X = data_set.drop(columns=['note', 'date'])
    y = data_set['note']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
    knn = KNeighborsRegressor(n_neighbors=5)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    
    from sklearn.metrics import mean_squared_error
    
    mse = mean_squared_error(y_test, y_pred)
    print(f'Mean Squared Error: {mse}')

    import requests
    import time
    import datetime

    from selenium import webdriver
    from selenium.webdriver.chrome.service import Service
    from selenium.webdriver.common.by import By
    
    path = "D:\chromedriver-win64\chromedriver.exe"
    service = Service(path)
    driver = webdriver.Chrome(service=service)
    
    # Récupération des données météorologiques actuelles à partir du site web
    path = "D:\\chromedriver-win64\\chromedriver.exe"
    service = Service(path)
    driver = webdriver.Chrome(service=service)

    current_date = datetime.date.today()
    url = f"https://www.meteoart.com/europe/france/ile-de-france/fontainebleau?page=past-weather#day={current_date.day}&month={current_date.month}"
    driver.get(url)
    driver.implicitly_wait(10)
    driver.find_element(By.CLASS_NAME, "fc-cta-consent").click()
    time.sleep(5)
    divs_month_data = driver.find_elements(By.CLASS_NAME, "month_data_to_animate")
    time.sleep(3)

    data = []
    txt = [current_date.strftime("%d/%m/%Y")]
    for div in divs_month_data:
        txt.append(div.text)

    data.append(txt)
    driver.quit()  # Fermer le navigateur

    # Créer un DataFrame pour les nouvelles données
    labels = ['date', 'tmp_max (°C)', 'tmp_min (°C)', 'precipitation (%)', 'wind (Km/h)', 'humidity (%)']
    new_weather_df = pd.DataFrame(data, columns=labels)

    # Normaliser les nouvelles données
    new_df = new_weather_df.drop(columns=['date'])
    new_df = new_df.replace(',', '.', regex=True).astype(float)
    new_date_weather_scaled = scaler.transform(new_df)

    # Prédire la note pour la nouvelle date
    predicted_note = knn.predict(new_date_weather_scaled)
    predicted_note_rounded = round(predicted_note[0])
    print(f'Predicted Note: {predicted_note_rounded}')'''